site_name: VimRFD Documents
pages:
    - Home: index.md
    - SourceCode/Debugging: SourceCode/Debugging.md
    - Features: UserManual/Features.md
    - Changelog: UserManual/Changelog.md
    - About: about.md
theme: windmillex


# vim:nocp:cin:sr:et:ts=4:sts=4:sw=4:ft=yaml:ff=unix:fenc=utf-8:
# EOF
