site_name: VimRFD Documents
pages:
    - Home: index.md
    - Changelog: UserManual/changelog.md
    - Features:  UserManual/features.md
    - Install:   UserManual/install.md
    - SourceCode/Debugging: SourceCode/debugging.md
    - About:     about.md
theme: windmillex

# vim:nocp:cin:sr:et:ts=4:sts=4:sw=4:ft=yaml:ff=unix:fenc=utf-8:
# EOF
